version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - sphinx-apidoc -f -e -o docs/api/ src/hyperelastic/

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .